name: slack_github_action

on:
  push:
    branches:
      - feedback_slack

jobs:
  slack_notifier:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build Maven project
        run: mvn clean install

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          slack-message: |
            {
              "text": "GitHub build result: ${{ job.status }}",
              "attachments": [
                {
                  "color": "${{ job.status == 'success' ? 'good' : 'danger' }}",
                  "fields": [
                    {
                      "title": "Commit Message",
                      "value": "${{ github.event.commits[0].message }}",
                      "short": false
                    },
                    {
                      "title": "Commit Author",
                      "value": "${{ github.event.commits[0].author.name }}",
                      "short": true
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
